# Main metainfo
log_save_dir: 'path/to/logs'
model_checkpoint_callback__monitor: 'avg_val_psnr'
model_checkpoint_callback__save_top_k: 5
model_checkpoint_callback__mode: 'max'
trainer__kwargs:
  max_epochs: 5
  track_grad_norm: 2
  fast_dev_run: True
  gpus: [0]

# Model
model: 'pan.PAN'
model__kwargs:
  in_nc: 3
  out_nc: 3
  nf: 40
  unf: 24
  nb: 16
  scale: 2

# Training
loss: 'l1'
lr_min: 1e-7
lr_max: 1e-3
betas: 
  - 0.9
  - 0.99
weight_decay: 0
T_0: 250e3
T_mult: 1
batch_size: 32

# Dataset
train_dataset__kwargs:
  gt_root: 'path/to/gt/folder'
  repeat_count: 5
  dtype: 'float32'
  device: 'cuda:0'
  scale_factor: .5
  interpolation_mode: 'bilinear'
  transform: 
    compose_as: 'nn.Sequential'
    transform: 
      - transform: RandomCrop
        args: [256]
      - transform: ColorJitter
        args: [0.2, 0.2, 0.2, 0.2]
      - transform: RandomHorizontalFlip
        args: [.5]
      - transform: RandomVerticalFlip
        args: [.5]
      - transform: RandomRotation90
        module: 'custom_transform'

val_dataset__kwargs:
  gt_root: 'path/to/gt/folder'
  dtype: 'float32'
  device: 'cuda:0'
  scale_factor: .5
  interpolation_mode: 'bilinear'
  transform:
    compose_as: 'nn.Sequential'
    transform: 
      - transform: CenterCrop
        args: [256]
